---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: 09:00
      timezone: Europe/Amsterdam

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      time: 09:00
      timezone: Europe/Amsterdam

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
