---
linters:
  disable-all: true
  enable:
    ## Default set
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    ## Additional
    - revive
    - goconst
    - gocyclo
    - gofumpt
    - goimports
    - nolintlint
    - predeclared
    - stylecheck
    - unconvert

linters-settings:
  # https://golangci-lint.run/usage/linters/#nolintlint
  nolintlint:
    # Enable to require an explanation of nonzero length after each nolint directive.
    # Default: false
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed.
    # Default: false
    require-specific: true
