// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package openapi

// Defines values for Result.
const (
	ResultN0 Result = 0

	ResultN1 Result = 1

	ResultN2 Result = 2

	ResultN3 Result = 3
)

// Defines values for Turn.
const (
	TurnN0 Turn = 0

	TurnN1 Turn = 1
)

// A side of the board
type BoardSide struct {
	// The pits of the board side
	Pits   []int64 `json:"pits"`
	Player Player  `json:"player"`

	// The store (big pit) of the board side
	Store int64 `json:"store"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Game defines model for Game.
type Game struct {
	// A side of the board
	BoardSide1 BoardSide `json:"board_side1"`

	// A side of the board
	BoardSide2 BoardSide `json:"board_side2"`

	// The id of the game
	Id string `json:"id"`

	// The result of the game. 0 => Undefined 1 => Player1Wins 2 => Player2Wins 3 => Tie
	Result Result `json:"result"`

	// The turn that needs to play next. 0 => Player1 1 => Player2
	Turn Turn `json:"turn"`
}

// Player defines model for Player.
type Player struct {
	// The name of the player
	Name string `json:"name"`

	// The score of the player
	Score int64 `json:"score"`
}

// The result of the game. 0 => Undefined 1 => Player1Wins 2 => Player2Wins 3 => Tie
type Result int

// The turn that needs to play next. 0 => Player1 1 => Player2
type Turn int

// GameID defines model for GameID.
type GameID string

// BadRequest defines model for BadRequest.
type BadRequest Error

// InternalServerError defines model for InternalServerError.
type InternalServerError Error

// NotFound defines model for NotFound.
type NotFound Error

// PlayCreated defines model for PlayCreated.
type PlayCreated struct {
	Game           Game  `json:"game"`
	PlayedPitIndex int64 `json:"played_pit_index"`
}

// NewGameBody defines model for NewGameBody.
type NewGameBody struct {
	Player1 string `json:"player1"`
	Player2 string `json:"player2"`
}

// NewPlayBody defines model for NewPlayBody.
type NewPlayBody struct {
	PitIndex int64 `json:"pit_index"`
}

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody NewGameBody

// CreatePlayJSONRequestBody defines body for CreatePlay for application/json ContentType.
type CreatePlayJSONRequestBody NewPlayBody

