// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mancala.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH
// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package proto

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Turn int32

const (
	Turn_TURN_UNSPECIFIED Turn = 0
	Turn_TURN_PLAYER1     Turn = 1
	Turn_TURN_PLAYER2     Turn = 2
)

// Enum value maps for Turn.
var (
	Turn_name = map[int32]string{
		0: "TURN_UNSPECIFIED",
		1: "TURN_PLAYER1",
		2: "TURN_PLAYER2",
	}
	Turn_value = map[string]int32{
		"TURN_UNSPECIFIED": 0,
		"TURN_PLAYER1":     1,
		"TURN_PLAYER2":     2,
	}
)

func (x Turn) Enum() *Turn {
	p := new(Turn)
	*p = x
	return p
}

func (x Turn) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Turn) Descriptor() protoreflect.EnumDescriptor {
	return file_mancala_proto_enumTypes[0].Descriptor()
}

func (Turn) Type() protoreflect.EnumType {
	return &file_mancala_proto_enumTypes[0]
}

func (x Turn) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Turn.Descriptor instead.
func (Turn) EnumDescriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{0}
}

type Result int32

const (
	Result_RESULT_UNSPECIFIED  Result = 0
	Result_RESULT_PLAYER1_WINS Result = 1
	Result_RESULT_PLAYER2_WINS Result = 2
	Result_RESULT_TIE          Result = 3
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "RESULT_PLAYER1_WINS",
		2: "RESULT_PLAYER2_WINS",
		3: "RESULT_TIE",
	}
	Result_value = map[string]int32{
		"RESULT_UNSPECIFIED":  0,
		"RESULT_PLAYER1_WINS": 1,
		"RESULT_PLAYER2_WINS": 2,
		"RESULT_TIE":          3,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_mancala_proto_enumTypes[1].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_mancala_proto_enumTypes[1]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{1}
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1       string                 `protobuf:"bytes,1,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       string                 `protobuf:"bytes,2,opt,name=player2,proto3" json:"player2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_mancala_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetPlayer1() string {
	if x != nil {
		return x.Player1
	}
	return ""
}

func (x *CreateGameRequest) GetPlayer2() string {
	if x != nil {
		return x.Player2
	}
	return ""
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedGame   *Game                  `protobuf:"bytes,1,opt,name=created_game,json=createdGame,proto3" json:"created_game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_mancala_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetCreatedGame() *Game {
	if x != nil {
		return x.CreatedGame
	}
	return nil
}

type FindGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindGameRequest) Reset() {
	*x = FindGameRequest{}
	mi := &file_mancala_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGameRequest) ProtoMessage() {}

func (x *FindGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGameRequest.ProtoReflect.Descriptor instead.
func (*FindGameRequest) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{2}
}

func (x *FindGameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindGameResponse) Reset() {
	*x = FindGameResponse{}
	mi := &file_mancala_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGameResponse) ProtoMessage() {}

func (x *FindGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGameResponse.ProtoReflect.Descriptor instead.
func (*FindGameResponse) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{3}
}

func (x *FindGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type ExecutePlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PitIndex      int64                  `protobuf:"varint,2,opt,name=pit_index,json=pitIndex,proto3" json:"pit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePlayRequest) Reset() {
	*x = ExecutePlayRequest{}
	mi := &file_mancala_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlayRequest) ProtoMessage() {}

func (x *ExecutePlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlayRequest.ProtoReflect.Descriptor instead.
func (*ExecutePlayRequest) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutePlayRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ExecutePlayRequest) GetPitIndex() int64 {
	if x != nil {
		return x.PitIndex
	}
	return 0
}

type ExecutePlayResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayedPitIndex int64                  `protobuf:"varint,1,opt,name=played_pit_index,json=playedPitIndex,proto3" json:"played_pit_index,omitempty"`
	Game           *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutePlayResponse) Reset() {
	*x = ExecutePlayResponse{}
	mi := &file_mancala_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlayResponse) ProtoMessage() {}

func (x *ExecutePlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlayResponse.ProtoReflect.Descriptor instead.
func (*ExecutePlayResponse) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutePlayResponse) GetPlayedPitIndex() int64 {
	if x != nil {
		return x.PlayedPitIndex
	}
	return 0
}

func (x *ExecutePlayResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Turn          Turn                   `protobuf:"varint,2,opt,name=turn,proto3,enum=mancala.Turn" json:"turn,omitempty"`
	Result        Result                 `protobuf:"varint,3,opt,name=result,proto3,enum=mancala.Result" json:"result,omitempty"`
	BoardSide1    *BoardSide             `protobuf:"bytes,4,opt,name=board_side1,json=boardSide1,proto3" json:"board_side1,omitempty"`
	BoardSide2    *BoardSide             `protobuf:"bytes,5,opt,name=board_side2,json=boardSide2,proto3" json:"board_side2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_mancala_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{6}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetTurn() Turn {
	if x != nil {
		return x.Turn
	}
	return Turn_TURN_UNSPECIFIED
}

func (x *Game) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_UNSPECIFIED
}

func (x *Game) GetBoardSide1() *BoardSide {
	if x != nil {
		return x.BoardSide1
	}
	return nil
}

func (x *Game) GetBoardSide2() *BoardSide {
	if x != nil {
		return x.BoardSide2
	}
	return nil
}

type BoardSide struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pits          []int64                `protobuf:"varint,1,rep,packed,name=pits,proto3" json:"pits,omitempty"`
	Store         int64                  `protobuf:"varint,2,opt,name=store,proto3" json:"store,omitempty"`
	Player        *Player                `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardSide) Reset() {
	*x = BoardSide{}
	mi := &file_mancala_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardSide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardSide) ProtoMessage() {}

func (x *BoardSide) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardSide.ProtoReflect.Descriptor instead.
func (*BoardSide) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{7}
}

func (x *BoardSide) GetPits() []int64 {
	if x != nil {
		return x.Pits
	}
	return nil
}

func (x *BoardSide) GetStore() int64 {
	if x != nil {
		return x.Store
	}
	return 0
}

func (x *BoardSide) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_mancala_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_mancala_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_mancala_proto_rawDescGZIP(), []int{8}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_mancala_proto protoreflect.FileDescriptor

const file_mancala_proto_rawDesc = "" +
	"\n" +
	"\rmancala.proto\x12\amancala\x1a\x1bbuf/validate/validate.proto\"Y\n" +
	"\x11CreateGameRequest\x12!\n" +
	"\aplayer1\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aplayer1\x12!\n" +
	"\aplayer2\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aplayer2\"F\n" +
	"\x12CreateGameResponse\x120\n" +
	"\fcreated_game\x18\x01 \x01(\v2\r.mancala.GameR\vcreatedGame\"!\n" +
	"\x0fFindGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x10FindGameResponse\x12!\n" +
	"\x04game\x18\x01 \x01(\v2\r.mancala.GameR\x04game\"^\n" +
	"\x12ExecutePlayRequest\x12 \n" +
	"\agame_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06gameId\x12&\n" +
	"\tpit_index\x18\x02 \x01(\x03B\t\xbaH\x06\"\x04\x10\x06(\x00R\bpitIndex\"b\n" +
	"\x13ExecutePlayResponse\x12(\n" +
	"\x10played_pit_index\x18\x01 \x01(\x03R\x0eplayedPitIndex\x12!\n" +
	"\x04game\x18\x02 \x01(\v2\r.mancala.GameR\x04game\"\xcc\x01\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04turn\x18\x02 \x01(\x0e2\r.mancala.TurnR\x04turn\x12'\n" +
	"\x06result\x18\x03 \x01(\x0e2\x0f.mancala.ResultR\x06result\x123\n" +
	"\vboard_side1\x18\x04 \x01(\v2\x12.mancala.BoardSideR\n" +
	"boardSide1\x123\n" +
	"\vboard_side2\x18\x05 \x01(\v2\x12.mancala.BoardSideR\n" +
	"boardSide2\"^\n" +
	"\tBoardSide\x12\x12\n" +
	"\x04pits\x18\x01 \x03(\x03R\x04pits\x12\x14\n" +
	"\x05store\x18\x02 \x01(\x03R\x05store\x12'\n" +
	"\x06player\x18\x03 \x01(\v2\x0f.mancala.PlayerR\x06player\"2\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score*@\n" +
	"\x04Turn\x12\x14\n" +
	"\x10TURN_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTURN_PLAYER1\x10\x01\x12\x10\n" +
	"\fTURN_PLAYER2\x10\x02*b\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESULT_PLAYER1_WINS\x10\x01\x12\x17\n" +
	"\x13RESULT_PLAYER2_WINS\x10\x02\x12\x0e\n" +
	"\n" +
	"RESULT_TIE\x10\x032\xdb\x01\n" +
	"\aService\x12E\n" +
	"\n" +
	"CreateGame\x12\x1a.mancala.CreateGameRequest\x1a\x1b.mancala.CreateGameResponse\x12?\n" +
	"\bFindGame\x12\x18.mancala.FindGameRequest\x1a\x19.mancala.FindGameResponse\x12H\n" +
	"\vExecutePlay\x12\x1b.mancala.ExecutePlayRequest\x1a\x1c.mancala.ExecutePlayResponseBw\n" +
	"\vcom.mancalaB\fMancalaProtoP\x01Z\x1egithub.com/pcriv/mancala/proto\xa2\x02\x03MXX\xaa\x02\aMancala\xca\x02\aMancala\xe2\x02\x13Mancala\\GPBMetadata\xea\x02\aMancalab\x06proto3"

var (
	file_mancala_proto_rawDescOnce sync.Once
	file_mancala_proto_rawDescData []byte
)

func file_mancala_proto_rawDescGZIP() []byte {
	file_mancala_proto_rawDescOnce.Do(func() {
		file_mancala_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mancala_proto_rawDesc), len(file_mancala_proto_rawDesc)))
	})
	return file_mancala_proto_rawDescData
}

var file_mancala_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mancala_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mancala_proto_goTypes = []any{
	(Turn)(0),                   // 0: mancala.Turn
	(Result)(0),                 // 1: mancala.Result
	(*CreateGameRequest)(nil),   // 2: mancala.CreateGameRequest
	(*CreateGameResponse)(nil),  // 3: mancala.CreateGameResponse
	(*FindGameRequest)(nil),     // 4: mancala.FindGameRequest
	(*FindGameResponse)(nil),    // 5: mancala.FindGameResponse
	(*ExecutePlayRequest)(nil),  // 6: mancala.ExecutePlayRequest
	(*ExecutePlayResponse)(nil), // 7: mancala.ExecutePlayResponse
	(*Game)(nil),                // 8: mancala.Game
	(*BoardSide)(nil),           // 9: mancala.BoardSide
	(*Player)(nil),              // 10: mancala.Player
}
var file_mancala_proto_depIdxs = []int32{
	8,  // 0: mancala.CreateGameResponse.created_game:type_name -> mancala.Game
	8,  // 1: mancala.FindGameResponse.game:type_name -> mancala.Game
	8,  // 2: mancala.ExecutePlayResponse.game:type_name -> mancala.Game
	0,  // 3: mancala.Game.turn:type_name -> mancala.Turn
	1,  // 4: mancala.Game.result:type_name -> mancala.Result
	9,  // 5: mancala.Game.board_side1:type_name -> mancala.BoardSide
	9,  // 6: mancala.Game.board_side2:type_name -> mancala.BoardSide
	10, // 7: mancala.BoardSide.player:type_name -> mancala.Player
	2,  // 8: mancala.Service.CreateGame:input_type -> mancala.CreateGameRequest
	4,  // 9: mancala.Service.FindGame:input_type -> mancala.FindGameRequest
	6,  // 10: mancala.Service.ExecutePlay:input_type -> mancala.ExecutePlayRequest
	3,  // 11: mancala.Service.CreateGame:output_type -> mancala.CreateGameResponse
	5,  // 12: mancala.Service.FindGame:output_type -> mancala.FindGameResponse
	7,  // 13: mancala.Service.ExecutePlay:output_type -> mancala.ExecutePlayResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_mancala_proto_init() }
func file_mancala_proto_init() {
	if File_mancala_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mancala_proto_rawDesc), len(file_mancala_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mancala_proto_goTypes,
		DependencyIndexes: file_mancala_proto_depIdxs,
		EnumInfos:         file_mancala_proto_enumTypes,
		MessageInfos:      file_mancala_proto_msgTypes,
	}.Build()
	File_mancala_proto = out.File
	file_mancala_proto_goTypes = nil
	file_mancala_proto_depIdxs = nil
}
